- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Pay-As-You-Go(1)(9737df6a-69a3-454a-912b-41ec9f513ce6)'
    appType: 'webAppLinux'
    WebAppName: 'followup-app-prod'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'NODE|10.16'
    enableCustomDeployment: true