// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

const appInsightsConnectionString =
  env['APP_INSIGHTS_CONNECTION_STRING'] || env['APPLICATIONINSIGHTS_CONNECTION_STRING'] || '';
const bootstrapApiKey = env['FOLLOWUP_API_KEY_AUTH'] || env['API_KEY_AUTH'] || '';

export const environment = {
  production: true,
  version: env.npm_package_version + '(alpha)',
  apiUrl: 'https://alpha-followup-api.azurewebsites.net/',
  apiKeyAuth: bootstrapApiKey,
  applicationInsights: {
    enabled: !!appInsightsConnectionString,
    connectionString: appInsightsConnectionString
  },
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US']
};
